# application.yml (최적화 버전)
spring:
  datasource:
    # 1. 호스트명을 summary-mysql 로 변경 (docker-compose 서비스 이름)
    url: jdbc:mysql://summary-mysql:3306/mydb?useSSL=false&serverTimezone=UTC
    username: myuser
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  application:
    name: summary-server

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: summary-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: com.yourorg.summary.adapter.in.message.dto
        spring.json.value.default.type: com.yourorg.summary.adapter.in.message.dto.SummaryConsumerDto


  gemini:
    api:
      key: "AIzaSyBKwtRlVcgFFlSzjSnl_2B-7dD1HhnnH4A"
      url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-Flash-latest:generateContent"
      model: "gemini-1.5-pro-latest"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
