version: '3.8'
services:
  strike-server:
    build: .
    container_name: recap-server
    ports:
      - "9004:9004"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - recap_net
networks:
  recap_net:
    driver: bridge
