version: '3.8'
services:
  strike-server:
    build: .
    container_name: article-server
    ports:
      - "9002:9002"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - article_net
networks:
  article_net:
    driver: bridge
