services:
  strike-server:
    build: .
    container_name: crawling-server
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - crawling_net
networks:
  crawling_net:
    driver: bridge
