# .github/workflows/cicd.yaml
name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]   # main 브랜치 push 시 실행
  workflow_dispatch:       # 수동 실행도 가능

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 도커 이미지 빌드(예: 모든 서비스)
      - name: Build and push Docker images
        run: |
          docker compose build
          docker compose push    # --push 필요시 옵션 확인

      # 서버에 SSH 접속해 docker-compose 재시작(운영서버에서)
      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/your-project    # 서버의 프로젝트 경로
            git pull                        # 코드/컴포즈 갱신
            docker compose down
            docker compose up -d --build
