# .github/workflows/cicd.yaml
name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]   # main 브랜치 push 시 실행
  workflow_dispatch:       # 수동 실행도 가능

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/your-project
            git pull
            docker compose down
            docker compose up -d --build
